name: 'Build Gradle project'
description: 'Build Gradle project skipping tests'

runs:
  using: 'composite'
  steps:
    - name: Build with Gradle
      run: ./gradlew build -x test
      shell: bash
