name: 'Build Docker image'
description: 'Build Docker image'

inputs:
  secret-github-token:
    description: 'The secrets.GITHUB_TOKEN secret for logging into GHCR'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR (Manual Docker Login)
      run: |
        echo "${{ inputs.secret-github-token }}" | docker login ghcr.io \
          --username ${{ github.actor }} \
          --password-stdin
      shell: bash

    - name: Build Docker Image
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}"
        IMAGE_NAME_LOWERCASE=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG=${{ github.sha }}

        echo "Building Docker image $IMAGE_NAME_LOWERCASE:$IMAGE_TAG"
        docker build . --file ./Dockerfile --tag $IMAGE_NAME_LOWERCASE:$IMAGE_TAG
      shell: bash

    - name: Push Docker Images to GHCR
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}"
        IMAGE_NAME_LOWERCASE=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG=${{ github.sha }}

        echo "Pushing Docker image $IMAGE_NAME_LOWERCASE:$IMAGE_TAG"
        docker push $IMAGE_NAME_LOWERCASE:$IMAGE_TAG

        if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_BASE_REF" == "main" ]]; then
          echo "Trigger is push to main, pushing $IMAGE_NAME_LOWERCASE:latest"
          docker tag $IMAGE_NAME_LOWERCASE:$IMAGE_TAG $IMAGE_NAME_LOWERCASE:latest
          docker push $IMAGE_NAME_LOWERCASE:latest
        fi
      shell: bash
