name: 'Test Java with Maven'
description: 'Test Java with Maven'

runs:
  using: 'composite'
  steps:
    - name: Run unit tests
      run: |
        mvn -B verify -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      shell: bash
